### ISSUE TITLE
Problem with incremental update of semantic summaries

### ISSUE THREAD

**Issue by pdhoolia** [pdhoolia/se-agent#12]
If there are push events where only non-code files have been updated, it seems the agent is updating the entire set of code files. It is behaving like a full onboard.

This is wrong. If there is a push event, and it only has non-code files only, we should not be treating it like a full onboard.

**Comment by se-agent** [comment]
To address the issue where the agent is updating all code files even when only non-code files are modified, we need to ensure that the `update_codebase_understanding` method in `project.py` only processes code files when they are modified.

Here are the relevant changes to make in the code:

### Changes in `project.py`

1. **Filter for Code Files**: When processing the list of modified files, ensure that only code files (e.g., Python files with `.py` extension) are considered for updating the semantic summaries.

Modify the relevant part in the `update_codebase_understanding` method to filter out non-code files.

```python
def update_codebase_understanding(self, modified_files=None):
    # ... existing code ...
    
    # If modified_files is None or empty, summarize all files
    if not modified_files:
        modified_files = []
        for root, _, files in os.walk(self.module_src_folder):
            for file in files:
                if file.endswith('.py'):
                    relative_path = os.path.relpath(os.path.join(root, file), self.module_src_folder)
                    modified_files.append(relative_path)
    else:
        # Filter out non-code files from the modified files list
        modified_files = [file for file in modified_files if file.endswith('.py')]

    # If there are no code files to process, return early
    if not modified_files:
        logger.info("No code files modified. Skipping update.")
        return

    # ... rest of the existing code ...
```

### Changes in `listener_core.py`

2. **Ensure Only Code Files Trigger Updates**: When processing the webhook event, ensure the list of modified files passed to `update_codebase_understanding` contains only code files.

Modify the `process_webhook` function to filter out non-code files before calling the update function.

```python
def process_webhook(data):
    # ... existing code ...

    # Handle push event to main branch
    if data.get('ref') == f'refs/heads/{project.info.main_branch}' and data.get('commits'):
        try:
            modified_files = {
                os.path.relpath(file, project.info.src_folder)
                for commit in data['commits']
                for file in commit.get('modified', []) + commit.get('added', [])
                if file.startswith(project.info.src_folder) and file.endswith('.py')  # Ensure only code files
            }
            if modified_files:  # Only update if there are code files
                project.update_codebase_understanding(modified_files)
                return {'status': 'Codebase understanding updated'}, 200
            else:
                logger.info("No code files changed in push event.")
                return {'status': 'No code files changed'}, 200
        except Exception as e:
            logger.exception("Error updating codebase understanding.")
            return {'status': 'error updating codebase understanding'}, 500

    return {'status': 'ignored event'}, 200
```

### Explanation

- **Filtering Modified Files**: By filtering the modified files in both the `update_codebase_understanding` method and the `process_webhook` function, we ensure that only Python files are processed for updates. This prevents unnecessary processing when non-code files are changed.
- **Early Return**: The code includes an early return if no code files are present in the modified list, avoiding redundant operations.
