### ISSUE TITLE
separation of concerns for api wrapping

### ISSUE THREAD

**Issue by pdhoolia** [pdhoolia/se-agent#5]
At the moment our implementation has mixed flask based wrrapping and the actual processing logic for events. Let's separate that out and also create an AWS Lambda function wrapper that uses the core processing logic.

**Comment by pdhoolia** [comment]
can you give me the full code for what the event processor file would look like.

**Comment by se-agent** [comment]
Certainly! Below is a full example of what the `event_processor.py` file might look like, encapsulating the core logic for processing issue events:

```python
# event_processor.py

import logging
from se_agent.issue_analyzer import analyze_issue
from se_agent.change_suggester import suggest_changes
from se_agent.localizer import localize_issue
from se_agent.project import Project

IGNORE_TOKEN = "IGNORE"

logger = logging.getLogger('se-agent-processor')
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter('[%(levelname)s] %(message)s'))
logger.addHandler(handler)

def process_issue_event(project: Project, issue_details, comment_details=None):
    """
    Processes new issues and issue comments, analyzing the issue, localizing it to specific files, and suggesting changes.
    """
    # Check if the comment is made by the agent itself
    if comment_details:
        if '<!-- SE Agent -->' in comment_details.get('body', ''):
            logger.debug("Ignoring agent's own comment")
            return IGNORE_TOKEN

    # Analyze, localize, and suggest changes for the issue
    try:
        analysis_results = analyze_issue(project, issue_details)
        logger.debug(f"Analysis results: {analysis_results}")
        localization_results = localize_issue(project, issue_details, analysis_results)
        logger.debug(f"Localization results: {localization_results}")
        change_suggestions = suggest_changes(project, analysis_results, localization_results)
        logger.debug(f"Change suggestions: {change_suggestions}")
    except Exception as e:
        logger.exception("Error processing issue.")
        return None

    # Get the issue number
    issue_number = issue_details['number']

    # Post the change suggestions as a comment on the GitHub issue
    try:
        # Include the special marker to identify agent's own comments
        agent_comment = f"<!-- SE Agent -->\n{change_suggestions}"
        project.post_issue_comment(issue_number, agent_comment)
    except Exception as e:
        logger.exception("Error posting comment to GitHub.")
        return None

    return change_suggestions
```

### Explanation

- **Logging**: A logger is set up specifically for the processor to debug and trace the processing of issues.

- **Functionality**: The `process_issue_event` function retains all the original functionality, including:
  - Checking if a comment is made by the agent itself to avoid processing it.
  - Analyzing the issue using `analyze_issue`.
  - Localizing the issue to specific files using `localize_issue`.
  - Suggesting changes using `suggest_changes`.
  - Posting comments back to GitHub for actionable insights.

- **Error Handling**: Exceptions are caught, logging the error and returning `None` if something goes wrong during processing or posting to GitHub.

This setup allows `event_processor.py` to serve as a central module, encapsulating the logic that can be reused in different contexts, such as in a Flask application or an AWS Lambda function.

**Comment by pdhoolia** [comment]
08f61d8

**Comment by se-agent** [comment]
It seems like you've provided a commit hash or a reference ID (`08f61d8`). If you need help related to this specific commit, such as analyzing the changes, understanding the context, or addressing any issues related to it, please provide more details or context around this commit. Let me know how I can assist you further!
